[features]
seeds = false
skip-lint = false

[programs.localnet]
multisig = "7YYnaRgQeHYd2FKGKkwASM2ZNZHTo1GvcicsyKKFvcoh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./.keys/upgrade-authority.json"

[scripts]
test = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/**/*.ts"
